### PR TITLE
Add missing locales.

### PR DESCRIPTION
**Pull request by limansky**
Hi everyone,

  I've found that there a lot of locales provide by AngularJS are missing (for example both ru-kz and kk-cyrl-kz using in Kazakhstan). So, I added all of them in `pom.xml` and `webjars-requirejs.js` files.

The list of locales currently supported in angular is here https://github.com/angular/angular.js/tree/master/src/ngLocale

### CODE REVIEW

**Comment by jamesward** [comment]
Thanks!  I'll release this shortly as `1.4.3-1`.

**Comment by limansky** [comment]
Great! Is it possible to backport this for 1.3.x branch?

**Comment by jamesward** [comment]
`1.3.17-1` will be released shortly.

**Comment by limansky** [comment]
Thanks a lot!

**Pull request merged**
